//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistanceCalculator.WcfService.ConsoleClient.DistanceCalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistanceCalculatorService.IDistanceCalculatorService")]
    public interface IDistanceCalculatorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistanceCalculatorService/CalcDistance", ReplyAction="http://tempuri.org/IDistanceCalculatorService/CalcDistanceResponse")]
        double CalcDistance(DistanceCalculator.Models.Point startPoint, DistanceCalculator.Models.Point endPoint);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDistanceCalculatorService/CalcDistance", ReplyAction="http://tempuri.org/IDistanceCalculatorService/CalcDistanceResponse")]
        System.Threading.Tasks.Task<double> CalcDistanceAsync(DistanceCalculator.Models.Point startPoint, DistanceCalculator.Models.Point endPoint);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDistanceCalculatorServiceChannel : DistanceCalculator.WcfService.ConsoleClient.DistanceCalculatorService.IDistanceCalculatorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistanceCalculatorServiceClient : System.ServiceModel.ClientBase<DistanceCalculator.WcfService.ConsoleClient.DistanceCalculatorService.IDistanceCalculatorService>, DistanceCalculator.WcfService.ConsoleClient.DistanceCalculatorService.IDistanceCalculatorService {
        
        public DistanceCalculatorServiceClient() {
        }
        
        public DistanceCalculatorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistanceCalculatorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistanceCalculatorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistanceCalculatorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalcDistance(DistanceCalculator.Models.Point startPoint, DistanceCalculator.Models.Point endPoint) {
            return base.Channel.CalcDistance(startPoint, endPoint);
        }
        
        public System.Threading.Tasks.Task<double> CalcDistanceAsync(DistanceCalculator.Models.Point startPoint, DistanceCalculator.Models.Point endPoint) {
            return base.Channel.CalcDistanceAsync(startPoint, endPoint);
        }
    }
}
